---
# tasks file for docker
  - name: Install a list of packages
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
      - python-setuptools
      update_cache: true

  #Get the Docker APT key located here - https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  #Get the Docker APT key located here - https://download.docker.com/linux/ubuntu/gpg
  - name: Add the APT Repo
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  
  #Install docker-ce using APT
  - name: Install docker-ce using APT
    apt:
     update_cache: true
     name: docker-ce
     state: latest

  #Check if docker is started
  - name: Checking docker is started
    service:
      name: docker
      state: started

  #Install the Docker pip package (Make sure Ansible is using pip3)
  - name: Install Dockers pip package
    pip:
      name: docker
      executable: pip3
  
  # Add your user to the docker group
  - name: Add user to docker group
    user: 
      name: jenkins
      groups: docker
      append: yes
  - name: restart connection to ensure user can complete docker commands
    meta: reset_connection
